site_name: AiHint Standard
site_description: An open standard for signed, verifiable metadata for websites
site_author: AiHint Contributors
site_url: https://docs.aihint.org/

repo_name: Ai-Hint/aihint-standard
repo_url: https://github.com/Ai-Hint/aihint-standard
edit_uri: edit/main/docs/

use_directory_urls: false

extra_javascript:
  - extra.js

extra_css:
  - assets/stylesheets/extra.css

theme:
  name: material
  custom_dir: overrides
  logo: assets/images/aihint-logo.png
  favicon: assets/images/aihint-logo.png
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo

plugins:
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"/`|]+'
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true

nav:
  - Home: index.md
  - Getting Started:
      - Choose Your Implementation: getting-started/choose-implementation.md
      - Quick Start: getting-started/quick-start.md
      - Installation: getting-started/installation.md
      - Key Concepts: getting-started/key-concepts.md
  - User Guide:
      - Implementation Guide: user-guide/implementation-guide.md
      - Key Management: user-guide/key-management.md
      - Example Workflows: user-guide/example-workflows.md
  - API Reference:
      - Python API: api-reference/python-api.md
      - JavaScript API: api-reference/javascript-api.md
      - PHP API: api-reference/php-api.md
      - CLI Reference: api-reference/cli-reference.md
  - Technical Reference:
      - Protocol & Data Model: technical/protocol.md
      - Signature Algorithm: technical/signatures.md
      - Security Considerations: technical/security-considerations.md
      - Trust Model: technical/trust-model.md
  - FAQ: technical/faq.md
  - Contributing:
      - How to Contribute: contributing/contributing.md
      - Code of Conduct: contributing/code-of-conduct.md
      - Security Policy: contributing/security.md
  - Changelog: changelog.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
      title: On this page 