import { signHint, verifyHint, validateHint, AiHint, generateKeys } from '../src/aihint';
import { TrustScoringEngine } from '../src/scoring/TrustScoringEngine';
import { TrustLevelHelper } from '../src/scoring/TrustLevel';
import * as fs from 'fs';
import * as path from 'path';

async function main() {
  console.log('=== Complete AiHint Workflow with Trust Scoring (TypeScript) ===\n');

  // Initialize the trust scoring engine
  const scoringEngine = new TrustScoringEngine();

  // Configuration
  const issuer = 'https://trust.aihint.org';
  const publicKeyUrl = 'https://trust.aihint.org/pubkey.pem';
  const privateKeyPath = path.join(__dirname, '../keys/private_key.pem');
  const publicKeyPath = path.join(__dirname, '../keys/public_key.pem');

  // Create keys directory if it doesn't exist
  const keysDir = path.dirname(privateKeyPath);
  if (!fs.existsSync(keysDir)) {
    fs.mkdirSync(keysDir, { recursive: true });
  }

  // Generate key pair if they don't exist
  if (!fs.existsSync(privateKeyPath) || !fs.existsSync(publicKeyPath)) {
    console.log('Generating RSA key pair...');
    generateKeys(privateKeyPath, publicKeyPath);
    console.log('Keys generated and saved to keys/ directory\n');
  }

  // URL to process
  const url = 'https://github.com';
  console.log(`Processing: ${url}`);
  console.log('-'.repeat(50));

  try {
    // Step 1: Get trust score
    console.log('Step 1: Calculating trust score...');
    const result = await scoringEngine.scoreWebsite(url);
    console.log(`✓ Trust score calculated: ${result.finalScore.toFixed(3)}`);
    console.log(`✓ Trust level: ${result.trustLevel} (${TrustLevelHelper.getDescription(result.trustLevel)})\n`);

    // Step 2: Create AiHint data structure
    console.log('Step 2: Creating AiHint data structure...');
    const aihintData: AiHint = {
      version: '0.1',
      type: 'global',
      target: url,
      issuer: issuer,
      score: result.finalScore,
      method: 'aihint-scoring-v1', // Use scoring method
      issued_at: new Date().toISOString(),
      expires_at: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(), // 1 year
      comment: `Trust score: ${result.finalScore.toFixed(3)} (Level: ${result.trustLevel}) - Generated by TypeScript AiHint`,
      public_key_url: publicKeyUrl
    };
    console.log('✓ AiHint object created');

    // Step 3: Validate AiHint
    console.log('Step 3: Validating AiHint...');
    const isValid = validateHint(aihintData);
    console.log(`✓ AiHint validation: ${isValid ? 'PASSED' : 'FAILED'}\n`);

    // Step 4: Sign the AiHint
    console.log('Step 4: Signing AiHint...');
    const signedAiHint = signHint(aihintData, privateKeyPath);
    console.log('✓ AiHint signed with private key\n');

    // Step 5: Verify the signature
    console.log('Step 5: Verifying signature...');
    const signatureValid = await verifyHint(signedAiHint, publicKeyPath);
    console.log(`✓ Signature verification: ${signatureValid ? 'PASSED' : 'FAILED'}\n`);

    // Step 6: Save the signed AiHint
    console.log('Step 6: Saving signed AiHint...');
    const filename = `signed_aihint_${new URL(url).hostname}.json`;
    fs.writeFileSync(filename, JSON.stringify(signedAiHint, null, 2));
    console.log(`✓ Saved to: ${filename}\n`);

    // Step 7: Display the complete AiHint
    console.log('Step 7: Final AiHint JSON:');
    console.log('-'.repeat(50));
    console.log(JSON.stringify(signedAiHint, null, 2));
    console.log('-'.repeat(50) + '\n');

    // Step 8: Test loading and verification
    console.log('Step 8: Testing load and verification...');
    const loadedData = JSON.parse(fs.readFileSync(filename, 'utf8'));
    const loadedValid = await verifyHint(loadedData, publicKeyPath);
    console.log(`✓ Loaded AiHint verification: ${loadedValid ? 'PASSED' : 'FAILED'}\n`);

    // Display scoring details
    console.log('Scoring Details:');
    console.log(`  Final Score: ${result.finalScore.toFixed(3)}`);
    console.log(`  Trust Level: ${result.trustLevel} (${TrustLevelHelper.getDescription(result.trustLevel)})`);
    console.log(`  Security Score: ${result.securityScore.toFixed(3)}`);
    console.log(`  Reputation Score: ${result.reputationScore.toFixed(3)}`);
    console.log(`  Compliance Score: ${result.complianceScore.toFixed(3)}`);
    console.log(`  Confidence: ${result.confidence.toFixed(3)}`);

    if (result.warnings.length > 0) {
      console.log(`  Warnings: ${result.warnings.length}`);
    }

    if (result.errors.length > 0) {
      console.log(`  Errors: ${result.errors.length}`);
    }

  } catch (error) {
    console.log(`Error: ${error instanceof Error ? error.message : 'Unknown error'}`);
    if (error instanceof Error && error.stack) {
      console.log('Stack trace:');
      console.log(error.stack);
    }
  }

  console.log('\n=== Workflow Complete ===');
}

main().catch(console.error);
